### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by mstembera** [zardav/FishBench#1]
First let me thank you for making this very useful tool!  Would it be possible to allow specifying the bench parameters so that we are not limited to the defaults?
Thanks!
Fisherman

**Comment by zardav** [comment]
Not for now... that will be easy, but I don't have the time. Maybe you do
it yourself and make pull request?

2015-09-17 3:02 GMT+02:00 mstembera notifications@github.com:

**Comment by mstembera** [comment]
I don't quite have the time either now but thanks for considering.  In the mean time I have been hacking up the defaults in SF if I really need it :)
